apiVersion: mxp.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: app-dev
  labels:
    system: prod
    api: prod
spec:
  writeConnectionSecretToRef:
    name: kubeconfig-app-dev
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-dev-providers
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./platform/system/production/providers
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-app-dev
      key: kubeconfig
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-dev-runtime
  namespace: flux-system
spec:
  dependsOn:
  - name: app-dev-providers
  interval: 1m0s
  path: ./runtime/production/apis-production/app-dev
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-app-dev
      key: kubeconfig
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-dev-apis
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./platform/apis/production
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-app-dev
      key: kubeconfig
