apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-dev-app-temp
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./dev
  prune: false
  sourceRef:
    kind: GitRepository
    name: team-blue
  kubeConfig:
    secretRef:
      name: kubeconfig-prod-dev
      key: kubeconfig