apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-example
spec:
  forProvider:
    chart:
      name: cert-manager
      repository: https://charts.jetstack.io
      version: 1.11.2
    namespace: cert-manager
  providerConfigRef:
    name: helm-incontrolplane
