apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsqlinstances.demo.upbound.io
spec:
  claimNames:
    kind: SQLInstance
    plural: sqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - host
  group: demo.upbound.io
  names:
    kind: XSQLInstance
    plural: xsqlinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              engine:
                type: string
                description: This RDS Instance engine, see https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html for possible values.
                enum:
                - postgres
                - mariadb
              engineVersion:
                type: string
                description: This RDS Instance engine version, see https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html for possible values.
              storageGB:
                type: integer
              initialDBName:
                type: string
              subnetIdSelector:
                type: object
                description: A selector to select Subnet resources.
                properties:
                  matchLabels:
                    type: object
                    description: A set of labels to select Subnet for the database instance.
                required:
                - matchLabels
              securityGroupIdSelector:
                type: object
                description: A selector to select SecurityGroup resources.
                properties:
                  matchLabels:
                    type: object
                    description: A set of labels to select SecurityGroup for the database instance.
                required:
                - matchLabels
            required:
              - engine
              - engineVersion
              - storageGB
              - subnetIdSelector
              - securityGroupIdSelector
