apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsqlinstances.aws.platformref.upbound.io
spec:
  claimNames:
    kind: SQLInstance
    plural: sqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - host
  group: aws.platformref.upbound.io
  names:
    kind: XSQLInstance
    plural: xsqlinstances
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  engine:
                    type: string
                    description: This RDS Instance engine, see https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html for possible values.
                    enum:
                    - postgres
                    - mariadb
                  engineVersion:
                    type: string
                    description: This RDS Instance engine version, see https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html for possible values.
                  storageGB:
                    type: integer
                  passwordSecretRef:
                    type: object
                    description: "A reference to the Secret object containing database password"
                    properties:
                      namespace:
                        type: string
                      name:
                        type: string
                      key:
                        type: string
                    required:
                    - namespace
                    - name
                    - key
                  clusterRef:
                    type: object
                    description: "A reference to the Network object that this database should be connected to."
                    properties:
                      id:
                        type: string
                        description: ID of the Network object this ref points to.
                    required:
                    - id
                required:
                  - engine
                  - engineVersion
                  - storageGB
                  - clusterRef
                  - passwordSecretRef
            required:
              - parameters
