apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xkubernetesclusters.demo.upbound.io
spec:
  group: demo.upbound.io
  names:
    kind: XKubernetesCluster
    plural: xkubernetesclusters
  claimNames:
    kind: KubernetesCluster
    plural: kubernetesclusters
  connectionSecretKeys:
  - kubeconfig
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: Cluster configuration parameters.
            properties:
              teams:
                type: array
                description: A list of teams that will deploy applications to this cluster.
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    repository:
                      type: string
                    environments:
                      type: array
                      description: Environments is a list of environments that should be deployed for this team.
                      default:
                        - name: dev
                          path: ./dev
                        - name: staging
                          path: ./staging
                        - name: production
                          path: ./production
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          path:
                            type: string
              nodes:
                type: object
                description: Cluster node configuration parameters.
                properties:
                  count:
                    type: integer
                    description: Desired node count, from 1 to 100.
                  size:
                    type: string
                    description: Size of node.
                    enum:
                    - small
                    - medium
                    - large
                required:
                - count
                - size
          status:
            type: object
            properties:
              publicSubnetIds:
                type: array
                items:
                  type: string
              subnetIds:
                type: array
                items:
                  type: string
              securityGroupIds:
                type: array
                items:
                  type: string
