apiVersion: mxp.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: prod-staging
  labels:
    system: prod
    api: staging
spec:
  writeConnectionSecretToRef:
    name: kubeconfig-prod-staging
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-staging-providers
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./platform/system/production/providers
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-prod-staging
      key: kubeconfig
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-staging-runtime
  namespace: flux-system
spec:
  dependsOn:
  - name: prod-staging-providers
  interval: 1m0s
  path: ./runtime/production/apis-staging
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-prod-staging
      key: kubeconfig
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-staging-apis
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./platform/apis/staging
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  kubeConfig:
    secretRef:
      name: kubeconfig-prod-staging
      key: kubeconfig
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: icp-prod-apis-staging-control-plane
spec:
  forProvider:
    assumeRolePolicy: |-
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::609897127049:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/755AE752658C7A29E3A092AEB155B06C"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringLike": {
                "oidc.eks.us-east-1.amazonaws.com/id/755AE752658C7A29E3A092AEB155B06C:aud": "sts.amazonaws.com",
                "oidc.eks.us-east-1.amazonaws.com/id/755AE752658C7A29E3A092AEB155B06C:sub": "system:serviceaccount:mcp-*-system:provider-aws-*"
              }
            }
          }
        ]
      }
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: icp-prod-apis-staging-control-plane
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AdministratorAccess
    roleRef:
      name: icp-prod-apis-staging-control-plane
