apiVersion: mxp.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: staging
  labels:
    platform: staging
spec:
  writeConnectionSecretToRef:
    name: kubeconfig-staging
    namespace: flux-system