apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: irsa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/eks-test-role
spec: {}
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: IRSA
---