apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.14.0
  controllerConfigRef:
    name: helm-incontrolplane
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: helm-incontrolplane
spec:
  serviceAccountName: helm-incontrolplane
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: helm-incontrolplane
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-incontrolplane
  namespace: upbound-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-incontrolplane
subjects:
  - kind: ServiceAccount
    name: helm-incontrolplane
    namespace: upbound-system
roleRef:
  kind: Role
  name: provider-install
  apiGroup: rbac.authorization.k8s.io
