apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworks.net.starter.org
spec:
  group: net.starter.org
  names:
    kind: XNetwork
    plural: xnetworks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
            status:
              type: object
              properties:
                subnetIds:
                  type: array
                  items:
                    type: string
                securityGroupIds:
                  type: array
                  items:
                    type: string
