apiVersion: mxp.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: app-staging
  labels:
    platform: prod
    api: prod
spec:
  writeConnectionSecretToRef:
    name: kubeconfig-app-staging
    namespace: flux-system